[package]
name = "safetensors_distributed"
version.workspace = true
edition.workspace = true

[dependencies]
reqwest = { workspace = true }
tokio = { workspace = true }
safetensors = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
futures-util = { workspace = true }
indicatif = "0.17.7"
serde = { version = "1.0.219", features = ["serde_derive"] }

[dev-dependencies]
axum = { workspace = true }
tempfile = { workspace = true }
tokio-test = { workspace = true }
