[package]
name = "safetensors_distributed"
version.workspace = true
edition.workspace = true

[dependencies]
reqwest = { version = "0.12.15", features = ["json", "stream"] }
tokio = { version = "1.37.0", features = ["rt-multi-thread", "macros"] }
safetensors = "0.4.0"
serde_json = "1.0.140"
thiserror = "2.0.12"
futures-util = "0.3.30"

[dev-dependencies]
axum = "0.7"
tempfile = "3.10.1"
tokio-test = "0.4.3"
