[package]
name = "safetensors_distributed_pyo3"
version.workspace = true
edition.workspace = true

[dependencies]
pyo3 = { version = "0.25.0", features = ["extension-module", "abi3", "abi3-py38"] }
reqwest = { version = "0.12.15", features = ["json", "stream"] }
tokio = { version = "1.37.0", features = ["rt-multi-thread", "macros"] }
safetensors = "0.4.0"
serde_json = "1.0.140"
thiserror = "2.0.12"
futures-util = "0.3.30"
axum = "0.7"

[dev-dependencies]
tempfile = "3.10.1"
warp = "0.3.6"
tokio-test = "0.4.3"
